### ISSUE TITLE
What is the licences of the stl files?

### ISSUE THREAD

**Issue by mxochicale** [pass810/Otto1_stl#1]
Hi @pass810 

Thanks for sharing such nice work. I am wondering what is the licence of the STL files? Can anyone use them, copy them or modify them? 

Regards
Miguel

**Comment by pass810** [comment]
Hello. Thank you for your comment.
I added license.txt in Otto1_library's repository. It is BSD license.
I think this licencs is as same as OttoDIY's one.
Sincerely
pass810
